general:
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: []

  focus_follows_cursor: true
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: "window_focus"

  hide_method: "cloak"
  show_all_in_taskbar: true

gaps:
  scale_with_dpi: true
  inner_gap: "4px"
  outer_gap:
    top: "4px"
    right: "4px"
    bottom: "4px"
    left: "4px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#83a598"

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      style: "square"

    transparency:
      enabled: false
      opacity: "95%"

  other_windows:
    border:
      enabled: true
      color: "#504945"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "100%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

workspaces:
  - name: "1"
    bind_to_monitor: 0
  - name: "2"
    bind_to_monitor: 0
  - name: "3"
    bind_to_monitor: 0
  - name: "4"
    bind_to_monitor: 0
  - name: "5"
    bind_to_monitor: 0
  - name: "6"
    bind_to_monitor: 0
  - name: "7"
    bind_to_monitor: 1
  - name: "8"
    bind_to_monitor: 1
  - name: "9"
    bind_to_monitor: 1
  - name: "10"
    bind_to_monitor: 1

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }
      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "EXCEL" }
        window_class: { not_regex: "XLMAIN" }
      - window_process: { equals: "WINWORD" }
        window_class: { not_regex: "OpusApp" }
      - window_process: { equals: "POWERPNT" }
        window_class: { not_regex: "PPTFrameClass" }
  - commands: ["set-floating --centered"]
    match:
      - window_title: { equals: "Calculator" }
        window_process: { equals: "ApplicationFrameHost" }
        window_class: { equals: "ApplicationFrameWindow" }
      # Generic popup/dialog windows.
      - window_class: { regex: '^#32770$|^MozillaDialogClass$|^SunAwtDialog$|^Chrome_WidgetWin_0$' }
      # Visual Studio dialogs/popups.
      - window_process: { equals: "devenv" }
        window_class: { regex: '^#32770$|^WindowsForms10\.Window\..*|^HwndWrapper\[DefaultDomain.*\]$' }
        window_title: { not_regex: '.* - Microsoft Visual Studio$|^Microsoft Visual Studio$' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+a"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+b"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["alt+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+g"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["alt+q"]

  # Kill GlazeWM process safely.
  # - commands: ["wm-exit"]
  #   bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+t"]

  # Redraw all windows.
  # - commands: ["wm-redraw"]
  #   bindings: ["alt+shift+w"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ["shell-exec %ProgramFiles%/WezTerm/wezterm-gui.exe"]
  - commands: ["shell-exec wt"]
    bindings: ["alt+enter"]

  - commands: ["shell-exec explorer"]
    bindings: ["alt+g"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace 10"]
    bindings: ["alt+0"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace 10", "focus --workspace 10"]
    bindings: ["alt+shift+0"]
