#################################
# AUTOSTART / DAEMONS / FIXES
#################################

# Notification
exec_always dunst

# RGB LEDs
exec_always openrgb --profile gruvbox.orp

# Dynamic Tiling Script
exec_always autotiling

# Polkit (Password dialog)
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id gnome-keyring-daemon --start --components=secrets,ssh

# Flatpak Fix
exec_always --no-startup-id /usr/libexec/xdg-desktop-portal --replace
exec_always export XDG_CURRENT_DESKTOP=sway

# ZapZap
exec flatpak run com.rtosta.zapzap

# Start GNOME Keyring
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_RUNTIME_DIR
exec_always /usr/bin/gnome-keyring-daemon --start --components=secrets,pkcs11

# Screen Share
exec --no-startup-id /usr/lib/xdg-desktop-portal -r

# Removable USB Auto mount
exec udiskie

# Enable portal for Discord Screen Sharing
exec systemctl --user set-environment XDG_CONFIG_HOME=/home/bgduke/.config
exec systemctl --user set-environment GTK_USE_PORTAL=0
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec systemctl --user restart pipewire-media-session xdg-desktop-portal xdg-desktop-portal-wlr

# Idle / Lock
# Catppuccin Mocha
# exec_always swayidle -w --color 1e1e2e \
#   timeout 3600 'swaymsg "output * dpms off"' \
#   resume 'swaymsg "output * dpms on"'

# Gruvbox
exec_always swayidle -w --color 282828 \
  timeout 3600 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"'

# Volume Fix
exec_always sleep 5 && pactl set-sink-volume @DEFAULT_SINK@ 90%
exec_always sleep 6 && pactl set-sink-volume @DEFAULT_SINK@ 100%

exec_always mkdir -p $SCREENSHOT_DIR
