#################################
# VARIABLES
#################################

set $mod Alt

set $left  h
set $down  j
set $up    k
set $right l

set $term --no-startup-id alacritty
set $menu --no-startup-id rofi -show drun -click-to-exit
set $menu_cmd --no-startup-id rofi -show run -click-to-exit

set $SCREENSHOT_DIR $HOME/Pictures/Screenshots
