#################################
# APPEARANCE
#################################

gaps outer 2
gaps inner 2

default_border pixel 2
default_floating_border pixel 2

# Nord Dark
set $bg0        #2e3440
set $bg1        #3b4252
set $bg2        #434c5e

set $fg0        #d8dee9
set $fg1        #eceff4

set $mauve      #b48ead
set $green      #a3be8c
set $red        #bf616a
set $orange     #d08770

# Catppuccin Mocha
# set $bg0        #181926
# set $bg1        #1e2030
# set $bg2        #24273a
#
# set $fg0        #cad3f5
# set $fg1        #b8c0e0
#
# set $mauve      #c6a0f6
# set $green      #a6da95
# set $red        #ed8796
# set $orange     #f5a97f

client.focused          $bg2  $mauve  $fg1 $fg0    $fg1
client.focused_inactive $bg2    $bg2    $fg0 $bg2    $bg2
client.unfocused        $bg1    $bg1    $fg0 $bg1    $bg1
client.urgent           $red    $red    $bg0 $red    $red

output * bg #2e3440 solid_color
