#################################
# APPEARANCE
#################################

gaps outer 4
gaps inner 4

default_border pixel 2
default_floating_border pixel 2

# Gruvbox Material Dark
set $bg0        #1d2021
set $bg1        #282828
set $bg2        #3c3836

set $fg0        #d4be98
set $fg1        #ddc7a1

set $mauve      #d3869b
set $green      #b8bb26
set $red        #ea6962
set $orange     #fe8019

# Catppuccin Mocha
# set $bg0        #181926
# set $bg1        #1e2030
# set $bg2        #24273a
#
# set $fg0        #cad3f5
# set $fg1        #b8c0e0
#
# set $mauve      #c6a0f6
# set $green      #a6da95
# set $red        #ed8796
# set $orange     #f5a97f

client.focused          $bg2  $mauve  $fg1 $fg0    $fg1
client.focused_inactive $bg2    $bg2    $fg0 $bg2    $bg2
client.unfocused        $bg1    $bg1    $fg0 $bg1    $bg1
client.urgent           $red    $red    $bg0 $red    $red

output * bg ~/Pictures/Wallpapers/jolyne-gruvbox.png fill
