#################################
# KEYBINDINGS
#################################

bindsym $mod+Return       exec $term
bindsym $mod+w            kill
bindsym $mod+d            exec $menu
bindsym alt+ctrl+d        exec $menu_cmd

bindsym $mod+Shift+r reload
bindsym $mod+Shift+e exec swaynag -t warning

bindsym $mod+e exec nemo
bindsym $mod+shift+b exec pkill waybar && waybar

# Lock Screen
bindsym $mod+alt+Shift+l exec swaylock -f --color 282828

floating_modifier $mod normal

# Volume wheel
bindsym XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Media
bindsym XF86AudioPlay exec playerctl play-pause

# Focus
bindsym $mod+$left  focus left
bindsym $mod+$down  focus down
bindsym $mod+$up    focus up
bindsym $mod+$right focus right

bindsym $mod+Left   focus left
bindsym $mod+Down   focus down
bindsym $mod+Up     focus up
bindsym $mod+Right  focus right

# Move
bindsym $mod+Shift+$left  move left
bindsym $mod+Shift+$down  move down
bindsym $mod+Shift+$up    move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+Left   move left 
bindsym $mod+Shift+Down   move down
bindsym $mod+Shift+Up     move up 
bindsym $mod+Shift+Right  move right 

# Outputs
bindsym $mod+Ctrl+$up move container to output up; focus up
bindsym $mod+Ctrl+$down move container to output down; focus down

bindsym $mod+space input * xkb_switch_layout next

# Workspaces
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9

bindsym $mod+Shift+1 move workspace 1; workspace 1 
bindsym $mod+Shift+2 move workspace 2; workspace 2 
bindsym $mod+Shift+3 move workspace 3; workspace 3 
bindsym $mod+Shift+4 move workspace 4; workspace 4 
bindsym $mod+Shift+5 move workspace 5; workspace 5 
bindsym $mod+Shift+6 move workspace 6; workspace 6 
bindsym $mod+Shift+7 move workspace 7; workspace 7 
bindsym $mod+Shift+8 move workspace 8; workspace 8 
bindsym $mod+Shift+9 move workspace 9; workspace 9 

# Layouts and window state
bindsym $mod+s layout stacking
bindsym $mod+g layout tabbed
bindsym $mod+v layout toggle split
bindsym $mod+x layout default

bindsym $mod+f fullscreen
bindsym $mod+t floating toggle; border pixel 2
bindsym alt+space focus mode_toggle
bindsym $mod+a focus parent

# Scratchpad
bindsym $mod+m move scratchpad
bindsym $mod+Shift+m scratchpad show

mode "resize" {
    bindsym $left  resize shrink width 80px
    bindsym $down  resize grow height 80px
    bindsym $up    resize shrink height 80px
    bindsym $right resize grow width 80px

    bindsym Left  resize shrink width 80px
    bindsym Down  resize grow height 80px
    bindsym Up    resize shrink height 80px
    bindsym Right resize grow width 80px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

mode "special" {
  bindsym c exec sh -c 'wl-color-picker clipboard; notify-send "Color copied"'; mode "default"

  bindsym s exec slurp | grim -g - - | wl-copy \
    && notify-send "Screenshot copied"; mode "default"

  bindsym a exec grim -g "$(slurp -o -f '%x,%y %wx%h')" \
    "$SCREENSHOT_DIR/screenshot-$(date +%Y%m%d-%H%M%S).png" \
    && notify-send "Window screenshot saved"; mode "default"

  bindsym Shift+s exec grim -g "$(slurp)" \
    "$SCREENSHOT_DIR/screenshot-$(date +%Y%m%d-%H%M%S).png" \
    && notify-send "Screenshot saved"; mode "default"

  bindsym f exec grim \
    "$SCREENSHOT_DIR/screenshot-$(date +%Y%m%d-%H%M%S).png" \
    && notify-send "Fullscreen screenshot saved"; mode "default"

  bindsym Escape mode "default"
  bindsym Return mode "default"
}

bindsym $mod+z mode "special"
