#################################
# VARIABLES
#################################

set $mod Super

set $left  h
set $down  j
set $up    k
set $right l

set $term --no-startup-id wezterm
set $menu --no-startup-id rofi -show drun -click-to-exit
set $menu_cmd --no-startup-id rofi -show run -click-to-exit
set $ws /home/bgduke/.config/sway/config.d/scripts/workspace.sh

set $SCREENSHOT_DIR $HOME/Pictures/Screenshots
