### Prefix & reload
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

### Terminal & input
set -g default-terminal "tmux-256color"

# Truecolor
set -sa terminal-features ",xterm-256color:RGB"
set -sa terminal-features ",kitty:RGB"

set -g focus-events on
set -g escape-time 10
set -g xterm-keys on
set -s extended-keys always
set -s extended-keys-format csi-u
set -as terminal-features ",xterm*:extkeys"
set -as terminal-features ",kitty:extkeys"

### Let Neovim handle mappings
unbind-key -q -n C--
unbind-key -q -n C-=
unbind-key -q C--
unbind-key -q C-=
unbind-key -q -n n

### Behavior
set -g history-limit 100000
set -g mouse on
set -g set-clipboard on

set -g renumber-windows on
set -g allow-rename off
set -g automatic-rename off
setw -g automatic-rename off

set -g base-index 1
setw -g pane-base-index 1

### Status bar
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left

set -g status-style "bg=default,fg=#a89984"
set -g message-style "bg=#3c3836,fg=#ebdbb2"
set -g mode-style "bg=#83a598,fg=#282828"

set -g status-left-length 20
set -g status-right-length 50

set -g status-left "#[fg=#83a598] #S #[default]"
set -g status-right "#[fg=#928374]#{b:pane_current_path} #[default]"

### Window list
setw -g window-status-style "bg=default,fg=#928374"
setw -g window-status-current-style "bg=default,fg=#ebdbb2"
setw -g window-status-activity-style "bg=default,fg=#fabd2f"
setw -g window-status-bell-style "bg=default,fg=#fb4934"

setw -g window-status-separator " "

setw -g window-status-format "#[fg=#928374]#I:#W#[default]"
setw -g window-status-current-format "#[fg=#ebdbb2]#I:#W#[default]"

### Panes
set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#83a598"

setw -g pane-border-status off

### Splits
bind | split-window -h
bind - split-window -v

### Pane navigation
bind H select-pane -L
bind J select-pane -D
bind K select-pane -U
bind L select-pane -R

## Windows
bind n new-window
bind q kill-window

### Window navigation
bind h previous-window
bind l next-window

### Toggle last pane
bind \\ select-pane -l

### Easier config editing
bind e new-window -n config "$EDITOR ~/.tmux.conf"
